### ISSUE TITLE
pdf(git): Style field does not have error checking and can be left empty

### ISSUE THREAD

**Issue by omehes** [openstax/output-producer-service#235]
when pdf(git) option is selected, the Style field does not have error check and I can submit a job without any style given. Should this be a required field with error when it is empty?

![9E8445BB-9722-40E6-91AF-6E16C11C4BC1_4_5005_c.jpeg](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/4b1abe08-067d-4602-ad9f-4c0843d7b7c0)

**Comment by tomjw64** [comment]
The validation was removed during development and was never added back. it should match the behavior of the non-git jobs.

**Comment by omehes** [comment]
verified in cops-staging
fixed

**Comment by omehes** [comment]
verified in cops.openstax.org
option: pdf(git)
when style field is left empty, error message is shown and cannot proceed to start a job: Style is required
fixed
regression tested cops
